rest_calls:
  - path: /api/v1/applications
    method: POST
    headers:
      Content-type: application/json
      Authorization: "{{TOKEN}}"
    payload:
      metadata:
        name: agrocd
      spec:
        destination:
          name: ''
          namespace: default
          server: 'https://kubernetes.default.svc'
        source:
          path: manifests
          repoURL: 'https://github.com/Einsteinish/ArgoCD.git'
          targetRevision: HEAD
        project: default
      name: ''
      namespace: default
      server: 'https://kubernetes.default.svc'
    response_format: json
    recoverable_codes: [400]
    response_translation:
        metadata: [metadata]
