rest_calls:
  - path: /api/v1/applications/{{NAME}}/sync
    method: POST
    headers:
      Content-type: application/json
      Authorization: "{{TOKEN}}"
    payload:
      name: "{{NAME}}"
    response_format: json
    recoverable_codes: [400]
    response_translation:
        metadata: [metadata]
